name: EVLUA_SCRIPT
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
env:
  RELEASE_VERSION: 0.0.1
jobs:
  build:
    name: build evlua
    runs-on: ubuntu-latest
    steps:
      - name: install apt dependencies
        run: |
          sudo apt-get update
          sudo apt install -y zlib1g
          sudo apt-get install -y zlib1g-dev cmake g++ build-essential clang liblzma-dev libssl-dev libreadline-dev autoconf libtool libsqlite3-dev wget zip pkg-config 
      
      - name: checkout evlua_build
        uses : actions/checkout@v3
        with :
          repository: Tekenlight/evlua_build
          path: evlua_build
      
      - name: build evlua
        run: |
          cd evlua_build
          bash ./evluaBuild -f -v ${{ env.RELEASE_VERSION }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          release_name: Release v${{ env.RELEASE_VERSION }}
          body: |
            Release Notes for v${{ env.RELEASE_VERSION }}:
            - Some notes

      - name: Upload .deb file for dev
        id: upload_dev_deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $HOME/executable/evlua-dev-${{ env.RELEASE_VERSION }}.dmg
          asset_name: evlua-dev-${{ env.RELEASE_VERSION }}.deb
          asset_content_type: application/x-deb
      
      - name: Upload .deb file for prod
        id: upload_deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $HOME/executable/evlua-${{ env.RELEASE_VERSION }}.dmg
          asset_name: evlua-${{ env.RELEASE_VERSION }}.deb
          asset_content_type: application/x-deb