name: EVLUA_DEB
on:
  workflow_dispatch:
  push:
    tags: 
      - "*"
jobs:
  build:
    name: build evlua
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: configure environment
        run: |
         echo "Building release: ${{  vars.RELEASE_VERSION }}"
         echo "INSTALLATION_PATH=$(pwd)/installation" >> "$GITHUB_ENV"
      
      - name: create installation directory
        run: |
          echo "All installables will be installed in $INSTALLATION_PATH"
          mkdir -p $INSTALLATION_PATH
          echo "Directory created"
          cd $INSTALLATION_PATH
          pwd
          ls -l
